import Navbar from '@/component/Navbar'
import './globals.css'
import Provider from '@/SessionProvider'
import Footer from '@/component/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      < Provider>
    <div className='container'>
    <Navbar />
        {children}
      <Footer />
    </div>   
   
      </Provider>
        
      </body>
    </html>
  )
}
